// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NetCoreHomework_20201206.Models
{
    public partial class Department_InsertResult
    {
        public int DepartmentID { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
